{{- if and .Values.persistence.enabled (not .Values.persistence.claimName) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mongodb.fullName" . }}-pvc
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
  {{- with .Values.persistence.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end}}
spec:
  accessModes:
  {{- range .Values.persistence.accessModes }}
  - {{ . | quote }}
  {{- end}}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
{{- end }}
