apiVersion: v2
name: mongodb
description: MongoDB is a relational open source NoSQL database.
type: application
version: 0.3.0
appVersion: 6.0.4-jammy
kubeVersion: ">= 1.24.3"
home: https://www.mongodb.com
sources:
- https://github.com/zmargeta/helm-charts
maintainers:
- name: zmargeta
  email: zeljko.margeta@gmail.com
